dist: xenial
language: python
cache: pip

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.5
          env: TOXENV=qa

install: pip install --ignore-installed --upgrade setuptools pip tox
script: tox -vv
